### ISSUE TITLE
Unable to create Oracle Image

### ISSUE THREAD

**Issue by ggulati2** [sciabarra/sites12c-docker#2] opened 2016-02-05 05:24 UTC
I am unable to create the oracle database image as it fails saying-

This system does not meet the minimum requirements for swap space.  Based on
the amount of physical memory available on the system, Oracle Database 11g
Express Edition requires 2048 MB of swap space. This system has 1535 MB
of swap space.  Configure more swap space on the system and retry the
installation.

**Comment by sciabarra** [comment] 2016-02-06 08:00
Oracle XE requires 2GB of virtual memory for installation. The script 0-machine-amazon.sh and 0-machine-virtual box both addresses the problem, the first adding 2gb swap in the amazon machine and the second building a machine with 8gb of memory. Can you provide details of the  environment you are using?

**Comment by ggulati2** [comment] 2016-02-09 17:31
I was able to fix this issue by increasing the swap of my underlying host linux machine.Thanks for your help.
However, after completing all the steps, I see a strange error after I login.It says - "you do not have access to any sites"

**Comment by msciab** [comment] 2016-02-09 18:58
It depends which user you use. If you use fwadmin, you should be able to access the AdminSite. If you use ContentServer you usually cannot and this is correct. Anyway if you see that message you have been authenticated.

**Comment by ggulati2** [comment] 2016-02-10 04:47
I used fwadmin only. I have used a new password while executing the 3-sites.sh instead of default password.Could that be the reason?

**Comment by sciabarra** [comment] 2016-02-10 07:34
No, the password you specify is used for all the inital users, fwadmin , ContentServer and Satellite. Sites needs to find itself when authenticating, and I experienced similar problems with some installation with firewalls blocking the access to the container. Basically from inside the container it cannot contact itself using the external host name. This is why I placed, in the docker-compose, an extra hosts saying "site.local: 127.0.0.1" (change site.local with the name you gave). 
Enter in the container with docker exec -ti ID bash and check the /etc/hosts there is a "127.0.0.1 sites.local) Also verify you generated a shared.loc pointing to the database. 
However from the description you should already be authenticated, the problem sounds more you have not completed the database creation (as shown in the video the 3-sites.sh perform the complete initialization and you should see all the messages produced by sites to complete the database creation).

**Comment by ggulati2** [comment] 2016-02-10 13:04
I tried to recreate the images and still getting the same error. I have verified all the things menitoned above :(

**Comment by ggulati2** [comment] 2016-02-10 13:10
I am not using amazon S3 and trying to build these images on my RHEL machine. Also, I have disabled the _machine.sh commands since it looks for docker-machine

**Comment by sciabarra** [comment] 2016-02-10 13:15
Can you please contact me and provide an access to your machine so I can check what is going on? You are using a configuration I have not tested with those scripts so I need to see to understand.

**Comment by ggulati2** [comment] 2016-02-10 13:17
Since this is an internal machine, I will not be able to provide access. Can I send you the logs from scripts I am executing? (1-download,2-weblogic and 3-sites) ? 
Email ID - michele.sciabarra@gmail.com

**Comment by sciabarra** [comment] 2016-02-10 13:19
yes - better if you share through dropbox or similar...

**Comment by ggulati2** [comment] 2016-02-11 05:47
I have shared the logs with you on google drive

**Comment by sciabarra** [comment] 2016-02-11 06:40
From the logs, Sites is properly installed. Please attach the docker-compose.yml, I need to see what the extra_host is.

**Comment by ggulati2** [comment] 2016-02-11 07:37
shared:
  image: localhost:5000/owcs/shared
  hostname: shared
  domainname: loc
  expose:
    - "1521"
sites:
  image: localhost:5000/owcs/sites
  hostname: sites
  domainname: loc
  links:
    - shared:shared.loc
  ports:
    - "7003:7003"
  extra_hosts:
    - "del2lkairos02v.sapient.com:127.0.0.1"

**Comment by sciabarra** [comment] 2016-02-11 08:08
Try this:
Enter in the container with 
docker exec -it $(docker ps | grep owcs/sites | awk '{print $1}') bash

then try

telnet del2lkairos02v.sapient.com 7003
telnet shared.loc

and verify you can connect.

Furthermore, did your password include "starange" characters like !" ? 
Then it is possible some characters were "eated" from the shell.
Do this 
grep password weblogic/user_projects/domains/base_domain/wcsites/wcsites/config/wcs_properties_bootstrap.ini

You should see which password was actually used.

**Comment by ggulati2** [comment] 2016-02-11 08:28
Hi,

I used the default password "xceladmin" when I recreated the images
Below is the output from telnet commands - 

[app@sites ~]$ telnet del2lkairos02v.sapient.com 7003
Trying 127.0.0.1...
Connected to del2lkairos02v.sapient.com.
Escape character is '^]'.
^]
telnet> quit
Connection closed.
[app@sites ~]$ telnet shared.loc
Trying 172.17.0.2...
telnet: connect to address 172.17.0.2: Connection refused
[app@sites ~]$ telnet shared.loc 1521
Trying 172.17.0.2...
Connected to shared.loc.
Escape character is '^]'.
^]

**Comment by ggulati2** [comment] 2016-02-11 08:29
#Default system administrator password 'password'
oracle.wcsites.system.admin.password=<saved in keystore>
#Default appplication password 'xceladmin'
oracle.wcsites.app.password=<saved in keystore>
#Default satellite server password 'password'
oracle.wcsites.satellite.password=<saved in keystore>
#LDAP password
oracle.wcsites.ldap.password=xceladmin

**Comment by sciabarra** [comment] 2016-02-11 08:31
I am confused. Everything is fine. The installation was completed properly hosts are seeing each other. What is your problem then? Cannot you connect with fwadmin/xceladmin? Can you please clean the cookies and try again?

**Comment by ggulati2** [comment] 2016-02-11 08:33
I tried to clean the cookies and tried. It gets authenticated but it says - You do not have access to any sites.

http://del2lkairos02v.sapient.com:7003/sites/wem/fatwire/wem/Welcome?ticket=ST-2-6S0Wc06zhlO3a9W2Mg5s-cas-del2lkairos02v.sapient.com-1

**Comment by sciabarra** [comment] 2016-02-11 08:39
what you see when you try to log in? Not even the administrative site?

**Comment by ggulati2** [comment] 2016-02-11 08:43
nopes .. It just says - You do not have access to any sites.

**Comment by ggulati2** [comment] 2016-02-11 10:31
Can you please suggest if anything else can be verified? I am stuck - could not find anything on google as well

**Comment by sciabarra** [comment] 2016-02-11 10:51
The installer worked. The configuration is correct. You can check the cas.log and the sites.log (using docker exec then going in the logs directory) to see if something hints why the cas is not giving the right role to the user. Looks like the database is somewhat corrupted so  I need to access to understand what is going wrong.

**Comment by ggulati2** [comment] 2016-02-11 11:10
Shall I try pointing to some other instance of database?

**Comment by sciabarra** [comment] 2016-02-11 11:42
you may try to enter in the shared database and verify if you can access to Sites tables. However the database is clearly accessible and the logs confirmed you created the database it so I am really puzzled why you do not have permissions to the AdminSite.

**Comment by sciabarra** [comment] 2016-02-11 14:27
can you please try to repeat the setup in the amazon cloud and give me access to the resulting image if it is broken too? I can give you an account for doing that if you do not have access to amazon, contact me by email.

**Comment by sciabarra** [comment] 2016-02-12 11:38
I replicated the issue! You used the master, not the v1 then. Working on understanding the problem.

**Comment by sciabarra** [comment] 2016-02-13 00:30
I confirm so far it still works on AmazonEC2 and in VirtualBox. But if you use the scripts in a local docker environment you have this problem. That was not a tested configuration. Nonetheless it is certainly a useful one so I am trying to understand the reason.

**Comment by sciabarra** [comment] 2016-02-14 01:45
Issue fixed in v1.0.1

**Closed as completed by sciabarra** 2016-02-14 01:45 UTC

**Comment by ggulati2** [comment] 2016-02-16 05:40
It is working now - thanks a lot
